routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});
Route::redirect('/','/login'); //TEMPORAL

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


Route::get('/home', 'HomeController@index')->middleware('auth','web')->name('home');

// RUTAS DE PROVEEDORES
Route::middleware(['auth','web'])->name('suppliers.')->prefix('suppliers')->group(function(){
    Route::get('/', 'SuppliersController@index')->name('index');
    Route::get('create','SuppliersController@create')->name('create');
    Route::get('show/{id}','SuppliersController@show')->where('id','[0-9]+')->name('show');
    Route::get('edit/{id}','SuppliersController@edit')->where('id','[0-9]+')->name('edit');

    Route::post('store','SuppliersController@store')->name('store');
    Route::post('update/{id}','SuppliersController@update')->where('id','[0-9]+')->name('update');
    Route::post('destroy','SuppliersController@destroy')->name('destroy');
});

//RUTAS CONSUMIBLES
Route::middleware(['auth','web'])->name('consumables.')->prefix('consumables')->group(function(){
    Route::get('/','ConsumablesController@index')->name('index');
    Route::get('create','ConsumablesController@create')->name('create');
    Route::get('show/{id}','ConsumablesController@show')->where('id','[0-9]+')->name('show');
    Route::get('edit/{id}','ConsumablesController@edit')->where('id','[0-9]+')->name('edit');
    Route::get('import', 'ConsumablesController@import')->name('import');

    Route::post('store', 'ConsumablesController@store')->name('store');
    Route::post('destroy', 'ConsumablesController@destroy')->name('destroy');
    Route::post('update/{id}','ConsumablesController@update')->where('id','[0-9]+')->name('update');
    Route::post('import/store','ConsumablesController@import_store')->name('import_store');
});

//RUTAS EQUIPO
Route::middleware(['auth','web'])->name('equipment.')->prefix('equipment')->group(function(){
    Route::get('/','EquipmentController@index')->name('index');
    Route::get('create','EquipmentController@create')->name('create');
    Route::get('show/{id}','EquipmentController@show')->where('id','[0-9]+')->name('show');
    Route::get('edit/{id}','EquipmentController@edit')->where('id','[0-9]+')->name('edit');
    Route::get('import','EquipmentController@import')->name('import');

    Route::post('destroy', 'EquipmentController@destroy')->name('destroy');
    Route::post('store', 'EquipmentController@store')->name('store');
    Route::post('update/{id}','EquipmentController@update')->where('id','[0-9]+')->name('update');
    Route::post('import/store','EquipmentController@import_store')->name('import_store');
});

//RUTAS DE PRESTAMOS
Route::middleware(['auth','web'])->name('loans.')->prefix('loans')->group(function(){
    Route::get('/','LoanController@index')->name('index');
    Route::get('/create','LoanController@create')->name('create');
    Route::get('/show/{id}','LoanController@show')->where('id','[0-9]+')->name('show');
    Route::get('/edit/{id}','LoanController@edit')->where('id','[0-9]+')->name('edit');

    Route::post('/store','LoanController@store')->name('store');
    Route::post('/update/{id}','LoanController@update')->name('update');
    Route::post('/destroy', 'LoanController@destroy')->name('destroy');
});

//RUTAS DE ORDEN DE COMPRAS
Route::middleware(['auth','web'])->name('purchase_orders.')->prefix('purchase_orders')->group(function(){
    Route::get('/', 'Purcharse_orderController@index')->name('index');
    Route::get('/create','Purcharse_orderController@create')->name('create');
    Route::get('/getItems/{id}','Purcharse_orderController@getItems')->where('id','[0-9]+')->name('getItems');
    Route::get('/getItem/{sku}','Purcharse_orderController@getItem')->name('getItem');
    Route::get('/order/{id}', 'Purcharse_orderController@edit')->where('id','[0-9]+')->name('edit');
    Route::get('/show/{id}', 'Purcharse_orderController@show')->where('id','[0-9]+')->name('show');

    Route::post('/store', 'Purcharse_orderController@store')->name('store');
    Route::post('/approve','Purcharse_orderController@approve')->name('approve');
    Route::post('/paid','Purcharse_orderController@paid')->name('paid');
    Route::post('/destroy', 'Purcharse_orderController@destroy')->name('destroy');
    Route::post('/update/{id}', 'Purcharse_orderController@update')->where('id','[0-9]+')->name('update');
});

//RUTAS PARA ORDENES DE ENTRADA
Route::middleware(['auth','web'])->name('income_orders.')->prefix('income_orders')->group(function(){
    Route::get('/','Income_orderController@index')->name('index');
    Route::get('/create','Income_orderController@create')->name('create');

    Route::post('/store','Income_orderController@store')->name('store');
});

//RUTAS PARA GASTOS
Route::middleware(['auth','web'])->name('expenditures.')->prefix('expenditures')->group(function(){
    Route::get('/', 'ExpenditureController@index')->name('index');
    Route::get('/create','ExpenditureController@create')->name('create');
    Route::get('/show/{id}','ExpenditureController@show')->where('id','[0-9]+')->name('show');
    Route::get('/edit/{id}','ExpenditureController@edit')->where('id','[0-9]+')->name('edit');

    Route::post('/store','ExpenditureController@store')->name('store');
    Route::post('/update/{id}','ExpenditureController@update')->where('id','[0-9]+')->name('update');
    Route::post('/destroy', 'ExpenditureController@destroy')->name('destroy');
});

//RUTAS PARA PROSPECTOS
Route::middleware(['auth','web'])->name('handbills.')->prefix('handbills')->group(function(){
    Route::get('/','HandbillController@index')->name('index');
    Route::get('/create','HandbillController@create')->name('create');
    Route::get('/edit/{id}','HandbillController@edit')->where('id','[0-9]+')->name('edit');

    Route::post('/store','HandbillController@store')->name('store');
    Route::post('/update/{id}','HandbillController@update')->where('id','[0-9]+')->name('update');
    Route::post('/destroy','HandbillController@destroy')->name('destroy');
});

//RUTAS PARA SERVICIOS
Route::middleware(['auth','web'])->name('services.')->prefix('services')->group(function(){
    Route::get('/', 'ServiceController@index')->name('index');
    Route::get('/create','ServiceController@create')->name('create');
    Route::get('/edit/{id}','ServiceController@edit')->where('id','[0-9]+')->name('edit');
    Route::get('/get_services/{price}','ServiceController@get_services')->name('get_services');

    Route::post('/store','ServiceController@store')->name('store');
    Route::post('/destroy','ServiceController@destroy')->name('destroy');
    Route::post('/update/{id}','ServiceController@update')->where('id','[0-9]+')->name('update');
});

//RUTAS PARA CLIENTES
Route::middleware(['auth','web'])->name('clients.')->prefix('clients')->group(function(){
    Route::get('/','ClientController@index')->name('index');
    Route::get('/create','ClientController@create')->name('create');
    Route::get('/check_rfc/{rfc}','ClientController@check_rfc')->name('check_rfc');
    Route::get('/price_list/{id}','ClientController@price_list')->name('price_list');

    Route::post('/store','ClientController@store')->name('store');
});

// RUTAS PARA COTIZACIONES
Route::middleware(['auth','web'])->name('quotations.')->prefix('quotations')->group(function(){
    Route::get('/', 'QuotationController@index')->name('index');
    Route::get('/create','QuotationController@create')->name('create');
    Route::get('/get_quotation/{id}','QuotationController@get_quotation')->name('get_quotation');

    Route::post('/store','QuotationController@store')->name('store');
    Route::post('/destroy','QuotationController@destroy')->name('destroy');
});

// RUTAS PARA REMISIONES
Route::middleware(['web','auth'])->name('referrals.')->prefix('referrals')->group(function(){
    Route::get('/','ReferralController@index')->name('index');
    Route::get('/create','ReferralController@create')->name('create');

    Route::post('/store','ReferralController@store')->name('store');
});

app/Loan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Loan extends Model
{
    public function user(){
        return $this->belongsTo(User::class);
    }
    public function equipment(){
        return $this->belongsTo(Equipment::class);
    }
}

app/Http/Controllers/LoanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\Loan;
use DateTime;
use App\Equipment;
use App\User;

class LoanController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->input('search');
        $loans = Loan::select('*', 'loans.id as id')
                            ->where(DB::raw("CONCAT(loans.applicant,' ',loans.initial_date,' ',loans.return_date,' ',users.name,' ',equipment.sku)"),'like',"%$search%")
                            ->join('equipment','equipment.id','loans.equipment_id')
                            ->join('users','users.id','loans.user_id')
                            ->paginate(15);

        return view('Loans.index', compact('search','loans'));
    }

    public function create()
    {
        $equipments = Equipment::whereStatus(true)->where('quantity','>','0')->get();
        foreach ($equipments as $equipment) {
            $current_loans = Loan::whereEquipment_id($equipment->id)->count();
            if($current_loans >= $equipment->quantity)
                unset($equipment);
        }
        if($equipments->isEmpty())
            return redirect()->route('loans.index')->withErrors('No hay equipo disponible para préstamo');

        return view('Loans.create',compact('equipments'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'equipment_id' => 'required|numeric|exists:equipment,id',
            'initial_date' => 'required|date|date_format:"Y-m-d"|after_or_equal:today',
            'return_date'  => 'required|date|date_format:"Y-m-d"|after_or_equal:initial_date',
            'applicant'    => 'required|min:3'
        ],[
            'equipment_id.required'       => 'El equipo a prestar es requerido',
            'equipment_id.numeric'        => 'El ID del equipo a prestar debe ser númerico',
            'equipment_id.exists'         => 'El ID del equipo a prestar es inválido',
            'initial_date.required'       => 'La fecha de préstamo es requerida',
            'initial_date.date'           => 'La fecha de préstamo no es válida',
            'initial_date.date_format'    => 'La fecha de préstamo no coincide con el formato Y-m-d',
            'initial_date.after_or_equal' => 'La fecha de préstamo debe ser igual o mayor a la fecha actual',
            'return_date.required'        => 'La fecha de retorno es requerida',
            'return_date.date'            => 'La fecha de retorno es inválida',
            'return_date.date_format'     => 'La fecha de retorno no coincide con el formato Y-m-d',
            'return_date.after_or_equal'  => 'La fecha de retorno debe ser igual o mayor que la fecha de préstamo',
            'applicant.required'          => 'El solicitante es requerido',
            'applicant.min'               => 'El nombre del solicitante debe tener almenos 3 caracteres'

        ]);

        $loan = new Loan();
        $loan->applicant    = $request->applicant;
        $loan->observations = $request->observations;
        $loan->initial_date = $request->initial_date;
        $loan->return_date  = $request->return_date;
        $loan->user_id      = Auth::user()->id;
        $loan->equipment_id = $request->equipment_id;

        $loan->save();

        return redirect()->route('loans.index')->withStatus('Préstamo registrado correctamente');

    }

    public function show($id)
    {
        $loan = Loan::findOrfail($id);

        return view('Loans.show', compact('loan'));
    }

    public function edit($id)
    {
        $equipments = Equipment::whereStatus(true)->get();
        $loan = Loan::findOrfail($id);

        return view('Loans.edit',compact('equipments','loan'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'equipment_id' => 'required|numeric|exists:equipment,id',
            'initial_date' => 'required|date|date_format:"Y-m-d"',
            'return_date'  => 'required|date|date_format:"Y-m-d"|after_or_equal:initial_date',
            'applicant'    => 'required|min:3'
        ],[
            'equipment_id.required'       => 'El equipo a prestar es requerido',
            'equipment_id.numeric'        => 'El ID del equipo a prestar debe ser númerico',
            'equipment_id.exists'         => 'El ID del equipo a prestar es inválido',
            'initial_date.required'       => 'La fecha de préstamo es requerida',
            'initial_date.date'           => 'La fecha de préstamo no es válida',
            'initial_date.date_format'    => 'La fecha de préstamo no coincide con el formato Y-m-d',
            'return_date.required'        => 'La fecha de retorno es requerida',
            'return_date.date'            => 'La fecha de retorno es inválida',
            'return_date.date_format'     => 'La fecha de retorno no coincide con el formato Y-m-d',
            'return_date.after_or_equal'  => 'La fecha de retorno debe ser igual o mayor que la fecha de préstamo',
            'applicant.required'          => 'El solicitante es requerido',
            'applicant.min'               => 'El nombre del solicitante debe tener almenos 3 caracteres'

        ]);

        $loan = Loan::findOrfail($id);
        $loan->applicant    = $request->applicant;
        $loan->observations = $request->observations;
        $loan->initial_date = $request->initial_date;
        $loan->return_date  = $request->return_date;

        $new_equipment = Equipment::findOrfail($request->equipment_id);
        if($new_equipment->id != $loan->equipment_id):

            $old_equipment = Equipment::findOrfail($loan->equipment_id);
            $old_equipment->status = true;
            $old_equipment->update();

            $loan->equipment_id = $request->equipment_id;

            $new_equipment->status = false;
            $new_equipment->update();

        endif;

        $loan->update();

        return redirect()->route('loans.index')->withStatus('Préstamo actualizado correctamente');

    }

    public function destroy(Request $request)
    {
        $loan = Loan::findOrfail($request->id);

        $equipment = Equipment::findOrfail($loan->equipment_id);
        $equipment->status = true;
        $equipment->update();

        $loan->delete();

        return redirect()->route('loans.index')->withStatus('Préstamo eliminado correctamente');
    }
}

resources/views/Loans/create.blade.php
@extends('layouts.app')
@section('title','CHRONOS - PRESTAMOS')
@section('prestamos','side-active')
@section('top-title','PRESTAMOS')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/create.css')}}">
@endsection
@section('content')

    <div class="container">
        <div class="row">
            <div class="col-12 text-center mb-3">
                <h4 class="title"><strong>{{__('REGISTRAR PRÉSTAMO')}}</strong></h4>
            </div>
            <form class="col-12" action="{{route('loans.store')}}" method="post">
                @csrf
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <select class="form-control create-input select-input" name="equipment_id" required>
                        <option value="" selected disabled>{{__('Equipo a prestar*')}}</option>
                        @foreach ($equipments as $equipment)
                            <option value="{{$equipment->id}}">{{$equipment->sku}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" name="initial_date" class="form-control create-input @error('initial_date') is-invalid @endif" value="{{old('initial_date')}}" placeholder="Fecha de préstamo*" onfocus="(this.type='date')" onblur="(this.type='text')" required>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" name="return_date" class="form-control create-input @error('return_date') is-invalid @endif" value="{{old('return_date')}}" placeholder="Fecha de retorno*" onfocus="(this.type='date')" onblur="(this.type='text')" required>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" name="applicant" class="form-control create-input @error('applicant') is-invalid @endif" value="{{old('applicant')}}" placeholder="Solicitante*" required>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" name="observations" class="form-control create-input @error('observations') is-invalid @endif" value="{{old('observations')}}" placeholder="Observaciones">
                </div>

                <div class="col-xl-6 mx-auto text-right buttons">
                    <a href="{{route('loans.index')}}" class="btn btn-link">{{__('CANCELAR')}}</a>
                    <button type="submit" class="btn submit-button py-2 px-5 rounded-0">{{__('CREAR')}}</button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/Loans/delete.blade.php
<div class="modal fade" id="delete" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-design">
            <div class="modal-header">
                <h5 class="modal-title">{{__('ATENCIÓN')}}</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('loans.destroy')}}" method="post">
                @csrf
                <div class="modal-body">
                    <input type="hidden" name="id" id="delete-id">
                    <p class="text-center">{{__('¿Realmente desea eliminar este elemento?')}}</p>
                    <p class="text-center">{{__('El préstamo se dará por finalizado, el equipo volverá a estar disponible.')}}</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link btn-modal-cancelar" data-dismiss="modal">
                        {{__('CANCELAR')}}
                    </button>
                    <button type="submit" class="btn btn-danger rounded-0 btn-modal-aceptar">
                        {{__('ACEPTAR')}}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/Loans/edit.blade.php
@extends('layouts.app')
@section('title','CHRONOS - PRESTAMOS')
@section('prestamos','side-active')
@section('top-title','PRESTAMOS')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/create.css')}}">
@endsection
@section('content')

    <div class="container">
        <div class="row">
            <div class="col-12 text-center mb-3">
                <h4 class="title"><strong>{{__('EDITAR PRÉSTAMO')}}</strong></h4>
            </div>
            <form class="col-12" action="{{route('loans.update',['id' => $loan->id])}}" method="post">
                @csrf
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <select class="form-control create-input select-input" name="equipment_id" required>
                        <option value="{{$loan->equipment_id}}" selected>{{$loan->equipment->sku}}</option>
                        @foreach ($equipments as $equipment)
                            <option value="{{$equipment->id}}">{{$equipment->sku}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" name="initial_date" class="form-control create-input @error('initial_date') is-invalid @endif" value="{{$loan->initial_date}}" placeholder="Fecha de préstamo*" onfocus="(this.type='date')" onblur="(this.type='text')" required>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" name="return_date" class="form-control create-input @error('return_date') is-invalid @endif" value="{{$loan->return_date}}" placeholder="Fecha de retorno*" onfocus="(this.type='date')" onblur="(this.type='text')" required>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" name="applicant" class="form-control create-input @error('applicant') is-invalid @endif" value="{{$loan->applicant}}" placeholder="Solicitante*" required>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" name="observations" class="form-control create-input @error('observations') is-invalid @endif" value="{{$loan->observations}}" placeholder="Observaciones">
                </div>

                <div class="col-xl-6 mx-auto text-right buttons">
                    <a href="{{route('loans.index')}}" class="btn btn-link">{{__('CANCELAR')}}</a>
                    <button type="submit" class="btn submit-button py-2 px-5 rounded-0">{{__('ACTUALIZAR')}}</button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/Loans/index.blade.php
@extends('layouts.app')
@section('title','CHRONOS - PRÉSTAMOS')
@section('prestamos','side-active')
@section('top-title','PRÉSTAMOS')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/index.css')}}">
@endsection
@section('content')

        <div class="container-fluid index-container">
            <div class="row">

                <div class="col-12 form-row">
                    <div class="col-xl-6">
                        <form action="" method="get">
                            <div class="input-group col-xl-8 mb-3">
                              <input type="text" class="form-control search-input rounded-0" name="search" value="{{$search}}" placeholder="BUSCAR" >
                              <div class="input-group-append">
                                <button class="btn btn-outline-secondary btn-search rounded-0" type="submit" >
                                    <i class="fas fa-search"></i>
                                </button>
                              </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-xl-6 text-right float-right">
                        <a href="{{route('loans.create')}}" class="btn index-button rounded-0 text-truncate"><strong>{{__('REGISTRAR PRÉSTAMO')}}</strong></a>
                    </div>
                </div>

                @if($loans->count())
                    <div class="col-12 table-responsive px-4 mt-4">
                        <table class="table">
                            <thead>
                                <tr class="text-center">
                                    <th>{{__('EQUIPO')}}</th>
                                    <th>{{__('FECHA')}}</th>
                                    <th>{{__('SOLICITANTE')}}</th>
                                    <th>{{__('FACILITADOR')}}</th>
                                    <th>{{__('ESTATUS')}}</th>
                                    <th>{{__('ACCIONES')}}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($loans as $loan)
                                    <tr class="text-center">
                                        <td class="align-middle text-truncate">{{$loan->equipment->sku}}</td>
                                        <td class="align-middle text-truncate">{{$loan->initial_date}}</td>
                                        <td class="align-middle text-truncate">{{$loan->applicant}}</td>
                                        <td class="align-middle text-truncate">{{$loan->user->name}}</td>
                                        <td class="align-middle text-truncate">{{$loan->status ? 'Activa' : 'Inactiva'}}</td>
                                        <td class="align-middle text-truncate">
                                            <a href="{{route('loans.show',['id' => $loan->id])}}" class="px-2" data-toggle="tooltip" data-placement="left" data-title="Mostrar">
                                                <i class="fas fa-clipboard-list icon-table"></i>
                                            </a>
                                            <a href="{{route('loans.edit',['id' => $loan->id])}}" class="px-2" data-toggle="tooltip" data-placement="top" data-title="Editar">
                                                <i class="fas fa-pencil-alt icon-table"></i>
                                            </a>
                                            <span class="open-modal" data-toggle="modal" data-target="#delete" data-action="delete" data-id="{{$loan->id}}">
                                                <button type="button" class="btn btn-link px-2" data-toggle="tooltip" data-placement="right" data-title="Eliminar">
                                                    <i class="fas fa-trash icon-table"></i>
                                                </button>
                                            </span>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="col-12">
                            <div class="col-md-8 col-sm-12 float-left form-inline select-count">

                            </div>
                            <div class="col-md-4 col-sm-12 float-right">
                                {{ $loans->appends(['search' => $search])->links() }}
                            </div>
                        </div>
                    </div>
                @else
                    <div class="col-12 text-center mt-5 sin-registros">
                        <i class="fas fa-exclamation-triangle fa-4x mb-2"></i>
                        <h4>{{__('SIN REGISTROS')}}</h4>
                    </div>
                @endif
            </div>
        </div>

        @include('Loans.delete');
@endsection
@section('scripts')
    <script src="{{asset('js/getID.js')}}" charset="utf-8"></script>
@endsection

resources/views/Loans/show.blade.php
@extends('layouts.app')
@section('title','CHRONOS - PRÉSTAMOS')
@section('prestamos','side-active')
@section('top-title','PRÉSTAMOS')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/show.css')}}">
@endsection
@section('content')

    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <h4 class="title">{{__('MOSTRAR PRÉSTAMO')}}</h4>
            </div>
            <div class="col-10 mx-auto mb-4 table-responsive mt-3">
                <table class="table text-center">
                    <thead>
                        <tr>
                            <th>{{__('CLAVE')}}</th>
                            <th>{{__('VALOR')}}</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><b>{{__('Equipo')}}</b></td>
                            <td>{{$loan->equipment->sku}}</td>
                        </tr>
                        <tr>
                            <td><b>{{__('Fecha de préstamo')}}</b></td>
                            <td>{{$loan->initial_date}}</td>
                        </tr>
                        <tr>
                            <td><b>{{__('Fecha de retorno')}}</b></td>
                            <td>{{$loan->return_date}}</td>
                        </tr>
                        <tr>
                            <td><b>{{__('Solicitante')}}</b></td>
                            <td>{{$loan->applicant}}</td>
                        </tr>
                        <tr>
                            <td><b>{{__('Facilitador')}}</b></td>
                            <td>{{$loan->user->name}}</td>
                        </tr>
                        <tr>
                            <td><b>{{__('Observaciones')}}</b></td>
                            <td>{{$loan->observations}}</td>
                        </tr>
                    </tbody>
                </table>
                <div class="col-12 text-center">
                    <a href="{{route('loans.index')}}" class="btn back-button rounded-0">{{__('ATRÁS')}}</a>
                </div>
            </div>
        </div>
    </div>

@endsection