routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});
Route::redirect('/','/login'); //TEMPORAL

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


Route::get('/home', 'HomeController@index')->middleware('auth','web')->name('home');

// RUTAS DE PROVEEDORES
Route::middleware(['auth','web'])->name('suppliers.')->prefix('suppliers')->group(function(){
    Route::get('/', 'SuppliersController@index')->name('index');
    Route::get('create','SuppliersController@create')->name('create');
    Route::get('show/{id}','SuppliersController@show')->where('id','[0-9]+')->name('show');
    Route::get('edit/{id}','SuppliersController@edit')->where('id','[0-9]+')->name('edit');

    Route::post('store','SuppliersController@store')->name('store');
    Route::post('update/{id}','SuppliersController@update')->where('id','[0-9]+')->name('update');
    Route::post('destroy','SuppliersController@destroy')->name('destroy');
});

//RUTAS CONSUMIBLES
Route::middleware(['auth','web'])->name('consumables.')->prefix('consumables')->group(function(){
    Route::get('/','ConsumablesController@index')->name('index');
    Route::get('create','ConsumablesController@create')->name('create');
    Route::get('show/{id}','ConsumablesController@show')->where('id','[0-9]+')->name('show');
    Route::get('edit/{id}','ConsumablesController@edit')->where('id','[0-9]+')->name('edit');
    Route::get('import', 'ConsumablesController@import')->name('import');

    Route::post('store', 'ConsumablesController@store')->name('store');
    Route::post('destroy', 'ConsumablesController@destroy')->name('destroy');
    Route::post('update/{id}','ConsumablesController@update')->where('id','[0-9]+')->name('update');
    Route::post('import/store','ConsumablesController@import_store')->name('import_store');
});

//RUTAS EQUIPO
Route::middleware(['auth','web'])->name('equipment.')->prefix('equipment')->group(function(){
    Route::get('/','EquipmentController@index')->name('index');
    Route::get('create','EquipmentController@create')->name('create');
    Route::get('show/{id}','EquipmentController@show')->where('id','[0-9]+')->name('show');
    Route::get('edit/{id}','EquipmentController@edit')->where('id','[0-9]+')->name('edit');
    Route::get('import','EquipmentController@import')->name('import');

    Route::post('destroy', 'EquipmentController@destroy')->name('destroy');
    Route::post('store', 'EquipmentController@store')->name('store');
    Route::post('update/{id}','EquipmentController@update')->where('id','[0-9]+')->name('update');
    Route::post('import/store','EquipmentController@import_store')->name('import_store');
});

//RUTAS DE PRESTAMOS
Route::middleware(['auth','web'])->name('loans.')->prefix('loans')->group(function(){
    Route::get('/','LoanController@index')->name('index');
    Route::get('/create','LoanController@create')->name('create');
    Route::get('/show/{id}','LoanController@show')->where('id','[0-9]+')->name('show');
    Route::get('/edit/{id}','LoanController@edit')->where('id','[0-9]+')->name('edit');

    Route::post('/store','LoanController@store')->name('store');
    Route::post('/update/{id}','LoanController@update')->name('update');
    Route::post('/destroy', 'LoanController@destroy')->name('destroy');
});

//RUTAS DE ORDEN DE COMPRAS
Route::middleware(['auth','web'])->name('purchase_orders.')->prefix('purchase_orders')->group(function(){
    Route::get('/', 'Purcharse_orderController@index')->name('index');
    Route::get('/create','Purcharse_orderController@create')->name('create');
    Route::get('/getItems/{id}','Purcharse_orderController@getItems')->where('id','[0-9]+')->name('getItems');
    Route::get('/getItem/{sku}','Purcharse_orderController@getItem')->name('getItem');
    Route::get('/order/{id}', 'Purcharse_orderController@edit')->where('id','[0-9]+')->name('edit');
    Route::get('/show/{id}', 'Purcharse_orderController@show')->where('id','[0-9]+')->name('show');

    Route::post('/store', 'Purcharse_orderController@store')->name('store');
    Route::post('/approve','Purcharse_orderController@approve')->name('approve');
    Route::post('/paid','Purcharse_orderController@paid')->name('paid');
    Route::post('/destroy', 'Purcharse_orderController@destroy')->name('destroy');
    Route::post('/update/{id}', 'Purcharse_orderController@update')->where('id','[0-9]+')->name('update');
});

//RUTAS PARA ORDENES DE ENTRADA
Route::middleware(['auth','web'])->name('income_orders.')->prefix('income_orders')->group(function(){
    Route::get('/','Income_orderController@index')->name('index');
    Route::get('/create','Income_orderController@create')->name('create');

    Route::post('/store','Income_orderController@store')->name('store');
});

//RUTAS PARA GASTOS
Route::middleware(['auth','web'])->name('expenditures.')->prefix('expenditures')->group(function(){
    Route::get('/', 'ExpenditureController@index')->name('index');
    Route::get('/create','ExpenditureController@create')->name('create');
    Route::get('/show/{id}','ExpenditureController@show')->where('id','[0-9]+')->name('show');
    Route::get('/edit/{id}','ExpenditureController@edit')->where('id','[0-9]+')->name('edit');

    Route::post('/store','ExpenditureController@store')->name('store');
    Route::post('/update/{id}','ExpenditureController@update')->where('id','[0-9]+')->name('update');
    Route::post('/destroy', 'ExpenditureController@destroy')->name('destroy');
});

//RUTAS PARA PROSPECTOS
Route::middleware(['auth','web'])->name('handbills.')->prefix('handbills')->group(function(){
    Route::get('/','HandbillController@index')->name('index');
    Route::get('/create','HandbillController@create')->name('create');
    Route::get('/edit/{id}','HandbillController@edit')->where('id','[0-9]+')->name('edit');

    Route::post('/store','HandbillController@store')->name('store');
    Route::post('/update/{id}','HandbillController@update')->where('id','[0-9]+')->name('update');
    Route::post('/destroy','HandbillController@destroy')->name('destroy');
});

//RUTAS PARA SERVICIOS
Route::middleware(['auth','web'])->name('services.')->prefix('services')->group(function(){
    Route::get('/', 'ServiceController@index')->name('index');
    Route::get('/create','ServiceController@create')->name('create');
    Route::get('/edit/{id}','ServiceController@edit')->where('id','[0-9]+')->name('edit');
    Route::get('/get_services/{price}','ServiceController@get_services')->name('get_services');

    Route::post('/store','ServiceController@store')->name('store');
    Route::post('/destroy','ServiceController@destroy')->name('destroy');
    Route::post('/update/{id}','ServiceController@update')->where('id','[0-9]+')->name('update');
});

//RUTAS PARA CLIENTES
Route::middleware(['auth','web'])->name('clients.')->prefix('clients')->group(function(){
    Route::get('/','ClientController@index')->name('index');
    Route::get('/create','ClientController@create')->name('create');
    Route::get('/check_rfc/{rfc}','ClientController@check_rfc')->name('check_rfc');
    Route::get('/price_list/{id}','ClientController@price_list')->name('price_list');

    Route::post('/store','ClientController@store')->name('store');
});

// RUTAS PARA COTIZACIONES
Route::middleware(['auth','web'])->name('quotations.')->prefix('quotations')->group(function(){
    Route::get('/', 'QuotationController@index')->name('index');
    Route::get('/create','QuotationController@create')->name('create');
    Route::get('/get_quotation/{id}','QuotationController@get_quotation')->name('get_quotation');

    Route::post('/store','QuotationController@store')->name('store');
    Route::post('/destroy','QuotationController@destroy')->name('destroy');
});

// RUTAS PARA REMISIONES
Route::middleware(['web','auth'])->name('referrals.')->prefix('referrals')->group(function(){
    Route::get('/','ReferralController@index')->name('index');
    Route::get('/create','ReferralController@create')->name('create');

    Route::post('/store','ReferralController@store')->name('store');
});

app/Purchase_order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Purchase_order extends Model
{
    public function supplier(){
        return $this->belongsTo(Supplier::class);
    }
    public function details(){
        return $this->hasMany(Purchase_detail::class);
    }
    public function approved_order(){
        return $this->belongsTo(Approved_order::class);
    }
}

resources/views/Purchase_orders/approve.blade.php
<div class="modal fade" id="approve" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-design">
            <div class="modal-header">
                <h5 class="modal-title">{{__('ATENCIÓN')}}</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('purchase_orders.approve')}}" method="post">
                @csrf
                <div class="modal-body text-center">
                    <p>{{__('¿Realmente desea aprobar esta orden de compra?')}}</p>
                    <p id="order-folio"></p>
                    <p id="order-amount"></p>
                    <input type="hidden" name="id" id="order-id" required>
                    <input type="text" name="comments" class="form-control create-input" placeholder="Comentarios">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link btn-modal-cancelar" data-dismiss="modal">
                        {{__('CANCELAR')}}
                    </button>
                    <button type="submit" class="btn btn-danger rounded-0 btn-modal-aceptar">
                        {{__('ACEPTAR')}}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/Purchase_orders/correct.blade.php
<div class="modal fade" id="correct" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-design">
            <div class="modal-header">
                <h4 class="modal-title">{{__('ATENCIÓN')}}</h4>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <p>{{$message}}</p>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-danger rounded-0 btn-modal-aceptar">
                    {{__('ACEPTAR')}}
                </button>
            </div>
        </div>
    </div>
</div>

resources/views/Purchase_orders/create.blade.php
@extends('layouts.app')
@section('title','CHRONOS - ÓRDENES DE COMPRA')
@section('orden_compra','side-active')
@section('top-title','ÓRDENES DE COMPRA')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/create.css')}}">
    <link rel="stylesheet" href="{{asset('css/layouts/index.css')}}">
@endsection
@section('content')

    <div class="container" id="purchase_orders">
        <div class="row">
            <div class="col-12 text-center mb-3">
                <h4 class="title"><strong>{{__('REGISTRAR ÓRDEN DE COMPRA')}}</strong></h4>
            </div>
            <form @submit="submitForm" class="col-12" action="" method="post" enctype="multipart/form-data">
                @csrf
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" v-model="date" name="date" class="form-control create-input @error('date') is-invalid @endif" placeholder="Fecha*"  value="{{old('date')}}"  onfocus="(this.type='date')" onblur="(this.type='text')" required>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <select v-model="supplier_id" class="form-control create-input select-input" @change="supplier($event)" name="supplier_id" id="supplier_id" required>
                        <option value="" disabled selected>{{__('Proveedor*')}}</option>
                        @foreach ($suppliers as $supplier)
                            <option value="{{$supplier->id}}">{{$supplier->business_name}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-5">
                    <div class="custom-file custom-file1 px-0">
                      <input type="file" name="file" class="custom-file-input" @change="filename($event)" id="file" required>
                      <label class="custom-file-label" id="label-file" for="customFile">@{{fileName}}</label>
                    </div>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <h5 class="title mb-3"><strong>{{__('AGREGAR EQUIPO/CONSUMIBLES')}}</strong></h5>
                    <select class="form-control create-input select-input" @change="item($event)" name="item" id="item">
                        <option value="" selected disabled>{{__('Equipo/Consumible*')}}</option>
                        <option v-for="item in items" :value="item.sku">@{{ item.description }}</option>
                    </select>
                    <div class="col-12 text-right px-0">
                        <button type="button" v-bind:class="{ disabled:addButton }" @click="addItem()" class="btn btn-link text-left px-0 text-decoration-none title add-button" id="add-button">
                            <strong>{{__('AGREGAR')}}</strong>
                        </button>
                    </div>
                </div>

                <div class="col-12 table-responsive mt-4" id="div-table" :class=" { 'table-hidden':tableHidden } ">
                    <table class="table" id="table-content">
                        <thead>
                            <tr>
                                <th>{{__('EQUIPO/CONSUMIBLE')}}</th>
                                <th>{{__('CANTIDAD')}}</th>
                                <th>{{__('IMPORTE')}}</th>
                                <th>{{__('SUBTOTAL')}}</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody id="table-content">
                            <tr v-for="(item, index) in selectedItems" :key="index" :item="item">
                                <td class="align-middle">@{{ item.description }}</td>
                                <td class="align-middle">
                                    <input type="number" class="create-input" name="quantity" min="1" @change="quantity($event,index)" @keyup="quantity($event,index)" :value="item.quantity">
                                </td>
                                <td class="align-middle">$@{{ item.initial_cost }}</td>
                                <td class="align-middle">$@{{item.subtotal}}</td>
                                <td class="align-middle">
                                    <button type="button" class="btn btn-link text-white" @click="removeRow(index)">
                                        <i class="fas fa-minus-circle fa-lg"></i>
                                    </button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="col-12 px-0 mt-4">
                        <div class="col-6 float-left title px-0">
                            <h5><strong>{{__('TOTAL')}}</strong></h5>
                        </div>
                        <div class="col-6 float-right px-0 text-right title">
                            <h5><strong>$@{{total_price}}</strong></h5>
                        </div>
                    </div>
                </div>
                <div class="col-12 px-0 text-right buttons" :class="{ 'table-hidden':tableHidden }"  style="margin-top: 40px">
                    <a href="{{route('purchase_orders.index')}}" class="btn btn-link">{{__('CANCELAR')}}</a>
                    <button type="submit" class="btn submit-button py-2 px-5 rounded-0" v-html="button_content">@{{button_content}}</button>
                </div>
            </form>
        </div>
    </div>

    @include('Purchase_orders.correct')

@endsection
@section('scripts')
    <script src="{{asset('js/vue.js')}}" charset="utf-8"></script>
    <script src="{{asset('js/axios.js')}}" charset="utf-8"></script>
    <script src="{{asset('js/purchase_orders.js')}}" charset="utf-8"></script>
@endsection

resources/views/Purchase_orders/destroy.blade.php
<div class="modal fade" id="destroy" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-design">
            <div class="modal-header">
                <h5 class="modal-title">{{__('ATENCIÓN')}}</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('purchase_orders.destroy')}}" method="post">
                @csrf
                <div class="modal-body text-center">
                    <p>{{__('¿Realmente desea eliminar esta órden de compra?')}}</p>
                    <input type="hidden" name="id" id="delete-id" required>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link btn-modal-cancelar" data-dismiss="modal">
                        {{__('CANCELAR')}}
                    </button>
                    <button type="submit" class="btn btn-danger rounded-0 btn-modal-aceptar">
                        {{__('ACEPTAR')}}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/Purchase_orders/index.blade.php
@extends('layouts.app')
@section('title','CHRONOS - ÓRDENES DE COMPRA')
@section('orden_compra','side-active')
@section('top-title','ÓRDENES DE COMPRA')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/index.css')}}">
    <link rel="stylesheet" href="{{asset('css/layouts/create.css')}}">
@endsection
@section('content')

    <div class="container-fluid index-container">
        <div class="row">

            <div class="col-12 form-row">
                <div class="col-xl-6">
                    <form action="" method="get">
                        <div class="input-group col-xl-8 mb-3">
                          <input type="text" class="form-control search-input rounded-0" name="search" value="{{$search}}" placeholder="BUSCAR" >
                          <div class="input-group-append">
                            <button class="btn btn-outline-secondary btn-search rounded-0" type="submit" >
                                <i class="fas fa-search"></i>
                            </button>
                          </div>
                        </div>
                    </form>
                </div>
                <div class="col-xl-6 text-right float-right">
                    <a href="{{route('purchase_orders.create')}}" class="btn index-button rounded-0 text-truncate"><strong>{{__('REGISTRAR OC')}}</strong></a>
                </div>
            </div>

            @if($orders->count())
                <div class="col-12 table-responsive px-4 mt-4">
                    <table class="table">
                        <thead>
                            <tr class="text-center">
                                <th>{{__('FOLIO')}}</th>
                                <th>{{__('FECHA')}}</th>
                                <th>{{__('PROVEEDOR')}}</th>
                                <th>{{__('IMPORTE')}}</th>
                                <th>{{__('ESTATUS')}}</th>
                                <th>{{__('PAGO')}}</th>
                                <th>{{__('ACCIONES')}}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($orders as $order)
                                <tr class="text-center">
                                    <td class="align-middle text-truncate">{{$order->folio}}</td>
                                    <td class="align-middle text-truncate">{{$order->date}}</td>
                                    <td class="align-middle text-truncate">{{$order->supplier->business_name}}</td>
                                    <td class="align-middle text-truncate">{{"$".$order->amount}}</td>
                                    <td class="align-middle text-truncate">{{$order->approved ? 'Aprobada' : 'Sin aprobar'}}</td>
                                    <td class="align-middle text-truncate">{{$order->paid ? 'Pagada' : 'Sin pagar'}}</td>
                                    <td class="align-middle text-truncate">
                                        <a href="{{route('purchase_orders.show', ['id' => $order->id])}}" class="btn btn-link" data-toggle="tooltip" data-placement="left" data-title="Mostrar">
                                            <i class="fas fa-clipboard-list icon-table"></i>
                                        </a>
                                        @if(!$order->approved)
                                            <a href="{{route('purchase_orders.edit', ['id' => $order->id])}}" class="btn btn-link" data-toggle="tooltip" data-placement="top" data-title="Editar">
                                                <i class="fas fa-pencil-alt icon-table"></i>
                                            </a>
                                            <span class="open-modal" data-toggle="modal" data-action="approve" data-target="#approve" data-id="{{$order->id}}" data-folio="{{$order->folio}}" data-amount="{{$order->amount}}">
                                                <button type="button" name="button" class="btn btn-link" data-toggle="tooltip" data-placement="top" data-title="Aprobar">
                                                    <i class="fas fa-check-square icon-table"></i>
                                                </button>
                                            </span>
                                        @endif
                                        @if(!$order->paid)
                                            <span class="open-modal" data-toggle="modal" data-action="pay" data-target="#pay" data-id="{{$order->id}}" data-folio="{{$order->folio}}" data-amount="{{$order->amount}}">
                                                <button type="button" name="button" class="btn btn-link" data-toggle="tooltip" data-placement="top" data-title="Pagar">
                                                    <i class="fas fa-money-bill-wave-alt icon-table"></i>
                                                </button>
                                            </span>
                                        @endif
                                        @if($order->paid == false && $order->approved == false)
                                            <span class="open-modal" data-toggle="modal" data-target="#destroy" data-action="delete" data-id="{{$order->id}}" >
                                                <button type="button" class="btn btn-link" data-toggle="tooltip" data-placement="right" data-title="Eliminar">
                                                    <i class="fas fa-trash-alt icon-table"></i>
                                                </button>
                                            </span>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="col-12">
                        <div class="col-md-8 col-sm-12 float-left form-inline select-count">

                        </div>
                        <div class="col-md-4 col-sm-12 float-right">
                            {{ $orders->appends(['search' => $search])->links() }}
                        </div>
                    </div>
                </div>
            @else
                <div class="col-12 text-center mt-5 sin-registros">
                    <i class="fas fa-exclamation-triangle fa-4x mb-2"></i>
                    <h4>{{__('SIN REGISTROS')}}</h4>
                </div>
            @endif

        </div>
    </div>

    @include('Purchase_orders.approve')
    @include('Purchase_orders.pay')
    @include('Purchase_orders.destroy')

@endsection
@section('scripts')
    <script src="{{asset('js/getID.js')}}" charset="utf-8"></script>
@endsection

resources/views/Purchase_orders/pay.blade.php
<div class="modal fade" id="pay" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-design">
            <div class="modal-header">
                <h5 class="modal-title">{{__('ATENCIÓN')}}</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('purchase_orders.paid')}}" method="post">
                @csrf
                <div class="modal-body text-center">
                    <p>{{__('¿Realmente desea cambiar el status de pago?')}}</p>
                    <p id="pay-folio"></p>
                    <p id="pay-amount"></p>
                    <input type="hidden" name="id" id="pay-id" required>
                    <input type="text" name="comments" class="form-control create-input" placeholder="Comentarios">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link btn-modal-cancelar" data-dismiss="modal">
                        {{__('CANCELAR')}}
                    </button>
                    <button type="submit" class="btn btn-danger rounded-0 btn-modal-aceptar">
                        {{__('ACEPTAR')}}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>