routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});
Route::redirect('/','/login'); //TEMPORAL

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


Route::get('/home', 'HomeController@index')->middleware('auth','web')->name('home');

// RUTAS DE PROVEEDORES
Route::middleware(['auth','web'])->name('suppliers.')->prefix('suppliers')->group(function(){
    Route::get('/', 'SuppliersController@index')->name('index');
    Route::get('create','SuppliersController@create')->name('create');
    Route::get('show/{id}','SuppliersController@show')->where('id','[0-9]+')->name('show');
    Route::get('edit/{id}','SuppliersController@edit')->where('id','[0-9]+')->name('edit');

    Route::post('store','SuppliersController@store')->name('store');
    Route::post('update/{id}','SuppliersController@update')->where('id','[0-9]+')->name('update');
    Route::post('destroy','SuppliersController@destroy')->name('destroy');
});

//RUTAS CONSUMIBLES
Route::middleware(['auth','web'])->name('consumables.')->prefix('consumables')->group(function(){
    Route::get('/','ConsumablesController@index')->name('index');
    Route::get('create','ConsumablesController@create')->name('create');
    Route::get('show/{id}','ConsumablesController@show')->where('id','[0-9]+')->name('show');
    Route::get('edit/{id}','ConsumablesController@edit')->where('id','[0-9]+')->name('edit');
    Route::get('import', 'ConsumablesController@import')->name('import');

    Route::post('store', 'ConsumablesController@store')->name('store');
    Route::post('destroy', 'ConsumablesController@destroy')->name('destroy');
    Route::post('update/{id}','ConsumablesController@update')->where('id','[0-9]+')->name('update');
    Route::post('import/store','ConsumablesController@import_store')->name('import_store');
});

//RUTAS EQUIPO
Route::middleware(['auth','web'])->name('equipment.')->prefix('equipment')->group(function(){
    Route::get('/','EquipmentController@index')->name('index');
    Route::get('create','EquipmentController@create')->name('create');
    Route::get('show/{id}','EquipmentController@show')->where('id','[0-9]+')->name('show');
    Route::get('edit/{id}','EquipmentController@edit')->where('id','[0-9]+')->name('edit');
    Route::get('import','EquipmentController@import')->name('import');

    Route::post('destroy', 'EquipmentController@destroy')->name('destroy');
    Route::post('store', 'EquipmentController@store')->name('store');
    Route::post('update/{id}','EquipmentController@update')->where('id','[0-9]+')->name('update');
    Route::post('import/store','EquipmentController@import_store')->name('import_store');
});

//RUTAS DE PRESTAMOS
Route::middleware(['auth','web'])->name('loans.')->prefix('loans')->group(function(){
    Route::get('/','LoanController@index')->name('index');
    Route::get('/create','LoanController@create')->name('create');
    Route::get('/show/{id}','LoanController@show')->where('id','[0-9]+')->name('show');
    Route::get('/edit/{id}','LoanController@edit')->where('id','[0-9]+')->name('edit');

    Route::post('/store','LoanController@store')->name('store');
    Route::post('/update/{id}','LoanController@update')->name('update');
    Route::post('/destroy', 'LoanController@destroy')->name('destroy');
});

//RUTAS DE ORDEN DE COMPRAS
Route::middleware(['auth','web'])->name('purchase_orders.')->prefix('purchase_orders')->group(function(){
    Route::get('/', 'Purcharse_orderController@index')->name('index');
    Route::get('/create','Purcharse_orderController@create')->name('create');
    Route::get('/getItems/{id}','Purcharse_orderController@getItems')->where('id','[0-9]+')->name('getItems');
    Route::get('/getItem/{sku}','Purcharse_orderController@getItem')->name('getItem');
    Route::get('/order/{id}', 'Purcharse_orderController@edit')->where('id','[0-9]+')->name('edit');
    Route::get('/show/{id}', 'Purcharse_orderController@show')->where('id','[0-9]+')->name('show');

    Route::post('/store', 'Purcharse_orderController@store')->name('store');
    Route::post('/approve','Purcharse_orderController@approve')->name('approve');
    Route::post('/paid','Purcharse_orderController@paid')->name('paid');
    Route::post('/destroy', 'Purcharse_orderController@destroy')->name('destroy');
    Route::post('/update/{id}', 'Purcharse_orderController@update')->where('id','[0-9]+')->name('update');
});

//RUTAS PARA ORDENES DE ENTRADA
Route::middleware(['auth','web'])->name('income_orders.')->prefix('income_orders')->group(function(){
    Route::get('/','Income_orderController@index')->name('index');
    Route::get('/create','Income_orderController@create')->name('create');

    Route::post('/store','Income_orderController@store')->name('store');
});

//RUTAS PARA GASTOS
Route::middleware(['auth','web'])->name('expenditures.')->prefix('expenditures')->group(function(){
    Route::get('/', 'ExpenditureController@index')->name('index');
    Route::get('/create','ExpenditureController@create')->name('create');
    Route::get('/show/{id}','ExpenditureController@show')->where('id','[0-9]+')->name('show');
    Route::get('/edit/{id}','ExpenditureController@edit')->where('id','[0-9]+')->name('edit');

    Route::post('/store','ExpenditureController@store')->name('store');
    Route::post('/update/{id}','ExpenditureController@update')->where('id','[0-9]+')->name('update');
    Route::post('/destroy', 'ExpenditureController@destroy')->name('destroy');
});

//RUTAS PARA PROSPECTOS
Route::middleware(['auth','web'])->name('handbills.')->prefix('handbills')->group(function(){
    Route::get('/','HandbillController@index')->name('index');
    Route::get('/create','HandbillController@create')->name('create');
    Route::get('/edit/{id}','HandbillController@edit')->where('id','[0-9]+')->name('edit');

    Route::post('/store','HandbillController@store')->name('store');
    Route::post('/update/{id}','HandbillController@update')->where('id','[0-9]+')->name('update');
    Route::post('/destroy','HandbillController@destroy')->name('destroy');
});

//RUTAS PARA SERVICIOS
Route::middleware(['auth','web'])->name('services.')->prefix('services')->group(function(){
    Route::get('/', 'ServiceController@index')->name('index');
    Route::get('/create','ServiceController@create')->name('create');
    Route::get('/edit/{id}','ServiceController@edit')->where('id','[0-9]+')->name('edit');
    Route::get('/get_services/{price}','ServiceController@get_services')->name('get_services');

    Route::post('/store','ServiceController@store')->name('store');
    Route::post('/destroy','ServiceController@destroy')->name('destroy');
    Route::post('/update/{id}','ServiceController@update')->where('id','[0-9]+')->name('update');
});

//RUTAS PARA CLIENTES
Route::middleware(['auth','web'])->name('clients.')->prefix('clients')->group(function(){
    Route::get('/','ClientController@index')->name('index');
    Route::get('/create','ClientController@create')->name('create');
    Route::get('/check_rfc/{rfc}','ClientController@check_rfc')->name('check_rfc');
    Route::get('/price_list/{id}','ClientController@price_list')->name('price_list');

    Route::post('/store','ClientController@store')->name('store');
});

// RUTAS PARA COTIZACIONES
Route::middleware(['auth','web'])->name('quotations.')->prefix('quotations')->group(function(){
    Route::get('/', 'QuotationController@index')->name('index');
    Route::get('/create','QuotationController@create')->name('create');
    Route::get('/get_quotation/{id}','QuotationController@get_quotation')->name('get_quotation');

    Route::post('/store','QuotationController@store')->name('store');
    Route::post('/destroy','QuotationController@destroy')->name('destroy');
});

// RUTAS PARA REMISIONES
Route::middleware(['web','auth'])->name('referrals.')->prefix('referrals')->group(function(){
    Route::get('/','ReferralController@index')->name('index');
    Route::get('/create','ReferralController@create')->name('create');

    Route::post('/store','ReferralController@store')->name('store');
});

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    
}

app/Http/Controllers/SuppliersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Supplier;

class SuppliersController extends Controller
{
    public function index(Request $request)
    {
        $search = $request->input('search');
        $count = Supplier::all()->count();
        $suppliers = Supplier::where(DB::raw("CONCAT(business_name,' ',tradename,' ',rfc,' ',email,' ',country,' ',state,' ',type,' ',phone)"),'like',"%$search%")->paginate(15);
        return view('Suppliers.index', compact('suppliers','search','count'));
    }

    public function create()
    {
        return view('Suppliers.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'business_name'   => 'required',
            'tradename'       => 'required',
            'rfc'             => 'required|max:13|min:12|alpha_num|unique:suppliers',
            'email'           => 'nullable|email',
            'external_number' => 'required|numeric',
            'zipcode'         => 'required|numeric|digits:5',
            'phone'           => 'nullable|numeric|digits:10',
        ],[
            'business_name.required'   => 'Razón social es requerido',
            'tradename.required'       => 'Nombre comercial es requerido',
            'rfc.required'             => 'El R.F.C. es requerido',
            'rfc.max'                  => 'El R.F.C. no puede ser mayor a 13 caracteres',
            'rfc.min'                  => 'El R.F.C. no puede ser menor a 12 caracteres',
            'rfc.alpha_numeric'        => 'El R.F.C. no puede contener caracteres especiales',
            'rfc.unique'               => 'El R.F.C. ingresado ya está en uso',
            'email.email'              => 'El Correo electónico no es válido',
            'external_number.required' => 'El No. exterior es requerido',
            'external_number.numeric'  => 'El No. exterior debe ser númerico',
            'zipcode.required'         => 'El código postal es requerido',
            'zipcode.numeric'          => 'El código postal debe ser númerico',
            'zipcode.digits'           => 'El código postal debe tener 5 caracteres',
            'phone.numeric'            => 'El teléfono debe ser númerico',
            'phone.digits'             => 'El teléfono no puede ser menor a 10 caracteres',
        ]);

        $supplier = new Supplier();

        $supplier->business_name         = $request->business_name;
        $supplier->tradename             = $request->tradename;
        $supplier->rfc                   = $request->rfc;
        $supplier->credit_days           = $request->credit_days;
        $supplier->credit_amount         = $request->credit_amount;
        $supplier->email                 = $request->email;
        $supplier->country               = $request->country;
        $supplier->state                 = $request->state;
        $supplier->municipality          = $request->municipality;
        $supplier->colony                = $request->colony;
        $supplier->street                = $request->street;
        $supplier->external_number       = $request->external_number;
        $supplier->internal_number       = $request->internal_number;
        $supplier->zipcode               = $request->zipcode;
        $supplier->phone                 = $request->phone;
        $supplier->contact_name          = $request->contact_name;
        $request->type ? $supplier->type = 'Compras' : $supplier->type = 'Gastos';

        $supplier->save();

        return redirect()->route('suppliers.index')->withStatus('Proveedor registrado correctamente');
    }
    public function show($id)
    {
        $supplier = Supplier::findOrfail($id);
        return view('Suppliers.show', compact('supplier'));
    }
    public function edit($id)
    {
        $supplier = Supplier::findOrfail($id);
        return view('Suppliers.edit', compact('supplier'));
    }
    public function update(Request $request, $id)
    {
        $request->validate([
            'business_name'   => 'required',
            'tradename'       => 'required',
            'rfc'             => 'required|max:13|min:12|alpha_num',
            'email'           => 'nullable|email',
            'external_number' => 'required|numeric',
            'zipcode'         => 'required|numeric|digits:5',
            'phone'           => 'nullable|numeric|digits:10',
        ],[
            'business_name.required'   => 'Razón social es requerido',
            'tradename.required'       => 'Nombre comercial es requerido',
            'rfc.required'             => 'El R.F.C. es requerido',
            'rfc.max'                  => 'El R.F.C. no puede ser mayor a 13 caracteres',
            'rfc.min'                  => 'El R.F.C. no puede ser menor a 12 caracteres',
            'rfc.alpha_numeric'        => 'El R.F.C. no puede contener caracteres especiales',
            'email.email'              => 'El Correo electónico no es válido',
            'external_number.required' => 'El No. exterior es requerido',
            'external_number.numeric'  => 'El No. exterior debe ser númerico',
            'zipcode.required'         => 'El código postal es requerido',
            'zipcode.numeric'          => 'El código postal debe ser númerico',
            'zipcode.digits'           => 'El código postal debe tener 5 caracteres',
            'phone.numeric'            => 'El teléfono debe ser númerico',
            'phone.digits'             => 'El teléfono no puede ser menor a 10 caracteres',
        ]);

        $supplier = Supplier::findOrfail($id);

        $supplier->business_name         = $request->business_name;
        $supplier->tradename             = $request->tradename;
        $supplier->rfc                   = $request->rfc;
        $supplier->credit_days           = $request->credit_days;
        $supplier->credit_amount         = $request->credit_amount;
        $supplier->email                 = $request->email;
        $supplier->country               = $request->country;
        $supplier->state                 = $request->state;
        $supplier->municipality          = $request->municipality;
        $supplier->colony                = $request->colony;
        $supplier->street                = $request->street;
        $supplier->external_number       = $request->external_number;
        $supplier->internal_number       = $request->internal_number;
        $supplier->zipcode               = $request->zipcode;
        $supplier->phone                 = $request->phone;
        $supplier->contact_name          = $request->contact_name;
        $request->type ? $supplier->type = 'Compras' : $supplier->type = 'Gastos';

        $supplier->update();

        return redirect()->route('suppliers.index')->withStatus('Proveedor actualizado correctamente');

    }
    public function destroy(Request $request)
    {
        $supplier = Supplier::findOrfail($request->id);
        $supplier->delete();

        return redirect()->route('suppliers.index')->withStatus('Proveedor eliminado correctamente');
    }
}

resources/views/Suppliers/create.blade.php
@extends('layouts.app')
@section('title','CHRONOS - PROVEEDORES')
@section('proveedores','side-active')
@section('top-title','PROVEEDORES')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/create.css')}}">
@endsection
@section('content')

    <div class="container">
        <div class="row">
            <div class="col-12 text-center mb-3">
                <h4 class="title"><strong>{{__('REGISTRAR PROVEEDOR')}}</strong></h4>
            </div>
            <form class="col-12" action="{{route('suppliers.store')}}" method="post">
                @csrf
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" name="business_name" class="form-control create-input @error('business_name') is-invalid @enderror" placeholder="Razón social*" value="{{old('business_name')}}" required>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" name="tradename" class="form-control create-input @error('tradename') is-invalid @enderror" placeholder="Nombre comercial*" value="{{old('tradename')}}" required>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" name="rfc" class="form-control create-input @error('rfc') is-invalid @enderror" placeholder="R.F.C*" value="{{old('rfc')}}" required>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" name="credit_days" class="form-control create-input @error('credit_days') is-invalid @enderror" placeholder="Días de crédito" value="{{old('credit_days')}}">
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" name="credit_amount" class="form-control create-input @error('credit_amount') is-invalid @enderror" placeholder="Monto del crédito" value="{{old('credit_amount')}}">
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="email" name="email" class="form-control create-input @error('email') is-invalid @enderror" placeholder="Correo electónico" value="{{old('email')}}">
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <select class="form-control create-input select-input" name="country" id="country" required>
                        <option value="" selected disabled>{{__('País*')}}</option>
                    </select>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" name="state" class="form-control create-input @error('state') is-invalid @enderror" placeholder="Estado*" value="{{old('state')}}" required>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" name="municipality" class="form-control create-input @error('municipality') is-invalid @enderror" placeholder="Municipio*" value="{{old('municipality')}}" required>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" name="colony" class="form-control create-input @error('colony') is-invalid @enderror" placeholder="Colonia" value="{{old('colony')}}">
                </div>
                <div class="form-group col-xl-6 mx-auto mb-3">
                    <input type="text" name="street" class="form-control create-input @error('street') is-invalid @enderror" placeholder="Calle" value="{{old('street')}}">
                </div>
                <div class="form-row col-xl-6 mx-auto mb-0">
                    <div class="form-group col-xl-6 px-0 mx-auto mb-3">
                        <input type="number" name="external_number" class="form-control create-input @error('external_number') is-invalid @enderror" placeholder="No. Exterior*" value="{{old('external_number')}}" required>
                    </div>
                    <div class="form-group col-xl-6 px-0 mx-auto mb-3">
                        <input type="text" name="internal_number" class="form-control create-input @error('internal_number') is-invalid @enderror" placeholder="No. Interior" value="{{old('internal_number')}}">
                    </div>
                    <div class="form-group col-xl-6 px-0 mx-auto mb-3">
                        <input type="number" name="zipcode" class="form-control create-input @error('zipcode') is-invalid @enderror" placeholder="Código postal*" value="{{old('zipcode')}}" required>
                    </div>
                    <div class="form-group col-xl-6 px-0 mx-auto mb-3">
                        <input type="number" name="phone" class="form-control create-input @error('phone') is-invalid @enderror" placeholder="Teléfono" value="{{old('phone')}}">
                    </div>
                    <div class="col-xl-6 px-1 text-left">
                        <p class="text-optional">Tipo de proveedor</p>
                    </div>
                    <div class="col-xl-6 px-0 custom-control text-center custom-switch">
                        <label for="" class="text-optional mr-5">Gastos</label>
                        <input type="checkbox" name="type" class="custom-control-input mx-5" id="type">
                        <label for="type" class="custom-control-label text-optional">Compras</label>
                    </div>
                </div>
                <div class="form-group col-xl-6 mx-auto mb-5">
                    <input type="text" name="contact_name" class="form-control create-input @error('contact_name') is-invalid @enderror" placeholder="Nombre de contacto" value="{{old('contact_name')}}">
                </div>
                <div class="col-xl-6 mx-auto text-right buttons">
                    <a href="{{route('suppliers.index')}}" class="btn btn-link cancel-button">
                        {{__('CANCELAR')}}
                    </a>
                    <button type="submit" class="btn submit-button rounded-0 py-2 px-5">
                        {{__('CREAR')}}
                    </button>
                </div>
            </form>
        </div>
    </div>

@endsection
@section('scripts')
    <script type="text/javascript">

        $(document).ready(function(){
            $.get("https://restcountries.eu/rest/v2/all", function(data){
                for (var i = 0; i < data.length; i++) {
                    var country = data[i].translations.es;
                    $('#country').append("<option value='"+country+"'>"+country+"</option>");
                }
            });
        });

    </script>
@endsection

resources/views/Suppliers/delete.blade.php
<div class="modal fade" id="delete" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-design">
            <div class="modal-header">
                <h5 class="modal-title">{{__('ATENCIÓN')}}</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('suppliers.destroy')}}" method="post">
                @csrf
                <div class="modal-body text-center">
                    <input type="hidden" name="id" id="delete-id">
                    <p>{{__('¿Realmente desea eliminar este elemento?')}}</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-link btn-modal-cancelar" data-dismiss="modal">
                        {{__('CANCELAR')}}
                    </button>
                    <button type="submit" class="btn btn-danger rounded-0 btn-modal-aceptar">
                        {{__('ACEPTAR')}}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/Suppliers/index.blade.php
@extends('layouts.app')
@section('title','CHRONOS - PROVEEDORES')
@section('proveedores','side-active')
@section('top-title','PROVEEDORES')
@section('styles')
    <link rel="stylesheet" href="{{asset('css/layouts/index.css')}}">
@endsection
@section('content')


    <div class="container-fluid index-container">
        <div class="row">
            <div class="col-12 form-row">
                <div class="col-xl-6">
                    <form action="" method="get">
                        <div class="input-group col-xl-8 mb-3">
                          <input type="text" class="form-control search-input rounded-0" name="search" value="{{$search}}" placeholder="BUSCAR" >
                          <div class="input-group-append">
                            <button class="btn btn-outline-secondary btn-search rounded-0" type="submit" >
                                <i class="fas fa-search"></i>
                            </button>
                          </div>
                        </div>
                    </form>
                </div>
                <div class="col-xl-6 text-right float-right">
                    <a href="{{route('suppliers.create')}}" class="btn index-button mr-auto rounded-0 text-truncate"><strong>{{__('REGISTRAR PROVEEDOR')}}</strong></a>
                </div>
            </div>

            @if($suppliers->count())
                <div class="col-12 table-responsive px-4 mt-4">
                    <table class="table">
                        <thead>
                            <tr class="text-center">
                                <th>{{__('NOMBRE')}}</th>
                                <th>{{__('CONTACTO')}}</th>
                                <th>{{__('CORREO')}}</th>
                                <th>{{__('TELÉFONO')}}</th>
                                <th>{{__('ACCIONES')}}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($suppliers as $supplier)
                                <tr class="text-center">
                                    <td class="align-middle text-truncate">{{$supplier->business_name   }}</td>
                                    <td class="align-middle text-truncate">{{$supplier->contact_name}}</td>
                                    <td class="align-middle text-truncate">{{$supplier->email}}</td>
                                    <td class="align-middle text-truncate">{{$supplier->phone}}</td>
                                    <td class="align-middle text-truncate">
                                        <a href="{{route('suppliers.show',['id' => $supplier->id])}}" class="px-2" data-toggle="tooltip" data-placement="left" data-title="Mostrar">
                                            <i class="fas fa-clipboard-list icon-table"></i>
                                        </a>
                                        <a href="{{route('suppliers.edit',['id' => $supplier->id])}}" class="px-2" data-toggle="tooltip" data-placement="top" data-title="Editar">
                                            <i class="fas fa-pencil-alt icon-table"></i>
                                        </a>
                                        <span class="open-modal" data-toggle="modal" data-target="#delete" data-action="delete" data-id="{{$supplier->id}}">
                                            <button type="button" class="btn btn-link px-2" data-toggle="tooltip" data-placement="right" data-title="Eliminar">
                                                <i class="fas fa-trash icon-table"></i>
                                            </button>
                                        </span>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="col-12">
                        <div class="col-md-8 col-sm-12 float-left form-inline select-count">

                        </div>
                        <div class="col-md-4 col-sm-12 float-right">
                            {{ $suppliers->appends(['search' => $search])->links() }}
                        </div>
                    </div>
                </div>
            @else
                <div class="col-12 text-center mt-5 sin-registros">
                    <i class="fas fa-exclamation-triangle fa-4x mb-2"></i>
                    <h4>{{__('SIN REGISTROS')}}</h4>
                </div>
            @endif
        </div>
    </div>

    @include('Suppliers.delete')

@endsection
@section('scripts')
    <script src="{{asset('js/getID.js')}}" charset="utf-8"></script>
@endsection