routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});
Route::redirect('/','/login'); //TEMPORAL

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


Route::get('/home', 'HomeController@index')->middleware('auth','web')->name('home');

// RUTAS DE PROVEEDORES
Route::middleware(['auth','web'])->name('suppliers.')->prefix('suppliers')->group(function(){
    Route::get('/', 'SuppliersController@index')->name('index');
    Route::get('create','SuppliersController@create')->name('create');
    Route::get('show/{id}','SuppliersController@show')->where('id','[0-9]+')->name('show');
    Route::get('edit/{id}','SuppliersController@edit')->where('id','[0-9]+')->name('edit');

    Route::post('store','SuppliersController@store')->name('store');
    Route::post('update/{id}','SuppliersController@update')->where('id','[0-9]+')->name('update');
    Route::post('destroy','SuppliersController@destroy')->name('destroy');
});

//RUTAS CONSUMIBLES
Route::middleware(['auth','web'])->name('consumables.')->prefix('consumables')->group(function(){
    Route::get('/','ConsumablesController@index')->name('index');
    Route::get('create','ConsumablesController@create')->name('create');
    Route::get('show/{id}','ConsumablesController@show')->where('id','[0-9]+')->name('show');
    Route::get('edit/{id}','ConsumablesController@edit')->where('id','[0-9]+')->name('edit');
    Route::get('import', 'ConsumablesController@import')->name('import');

    Route::post('store', 'ConsumablesController@store')->name('store');
    Route::post('destroy', 'ConsumablesController@destroy')->name('destroy');
    Route::post('update/{id}','ConsumablesController@update')->where('id','[0-9]+')->name('update');
    Route::post('import/store','ConsumablesController@import_store')->name('import_store');
});

//RUTAS EQUIPO
Route::middleware(['auth','web'])->name('equipment.')->prefix('equipment')->group(function(){
    Route::get('/','EquipmentController@index')->name('index');
    Route::get('create','EquipmentController@create')->name('create');
    Route::get('show/{id}','EquipmentController@show')->where('id','[0-9]+')->name('show');
    Route::get('edit/{id}','EquipmentController@edit')->where('id','[0-9]+')->name('edit');
    Route::get('import','EquipmentController@import')->name('import');

    Route::post('destroy', 'EquipmentController@destroy')->name('destroy');
    Route::post('store', 'EquipmentController@store')->name('store');
    Route::post('update/{id}','EquipmentController@update')->where('id','[0-9]+')->name('update');
    Route::post('import/store','EquipmentController@import_store')->name('import_store');
});

//RUTAS DE PRESTAMOS
Route::middleware(['auth','web'])->name('loans.')->prefix('loans')->group(function(){
    Route::get('/','LoanController@index')->name('index');
    Route::get('/create','LoanController@create')->name('create');
    Route::get('/show/{id}','LoanController@show')->where('id','[0-9]+')->name('show');
    Route::get('/edit/{id}','LoanController@edit')->where('id','[0-9]+')->name('edit');

    Route::post('/store','LoanController@store')->name('store');
    Route::post('/update/{id}','LoanController@update')->name('update');
    Route::post('/destroy', 'LoanController@destroy')->name('destroy');
});

//RUTAS DE ORDEN DE COMPRAS
Route::middleware(['auth','web'])->name('purchase_orders.')->prefix('purchase_orders')->group(function(){
    Route::get('/', 'Purcharse_orderController@index')->name('index');
    Route::get('/create','Purcharse_orderController@create')->name('create');
    Route::get('/getItems/{id}','Purcharse_orderController@getItems')->where('id','[0-9]+')->name('getItems');
    Route::get('/getItem/{sku}','Purcharse_orderController@getItem')->name('getItem');
    Route::get('/order/{id}', 'Purcharse_orderController@edit')->where('id','[0-9]+')->name('edit');
    Route::get('/show/{id}', 'Purcharse_orderController@show')->where('id','[0-9]+')->name('show');

    Route::post('/store', 'Purcharse_orderController@store')->name('store');
    Route::post('/approve','Purcharse_orderController@approve')->name('approve');
    Route::post('/paid','Purcharse_orderController@paid')->name('paid');
    Route::post('/destroy', 'Purcharse_orderController@destroy')->name('destroy');
    Route::post('/update/{id}', 'Purcharse_orderController@update')->where('id','[0-9]+')->name('update');
});

//RUTAS PARA ORDENES DE ENTRADA
Route::middleware(['auth','web'])->name('income_orders.')->prefix('income_orders')->group(function(){
    Route::get('/','Income_orderController@index')->name('index');
    Route::get('/create','Income_orderController@create')->name('create');

    Route::post('/store','Income_orderController@store')->name('store');
});

//RUTAS PARA GASTOS
Route::middleware(['auth','web'])->name('expenditures.')->prefix('expenditures')->group(function(){
    Route::get('/', 'ExpenditureController@index')->name('index');
    Route::get('/create','ExpenditureController@create')->name('create');
    Route::get('/show/{id}','ExpenditureController@show')->where('id','[0-9]+')->name('show');
    Route::get('/edit/{id}','ExpenditureController@edit')->where('id','[0-9]+')->name('edit');

    Route::post('/store','ExpenditureController@store')->name('store');
    Route::post('/update/{id}','ExpenditureController@update')->where('id','[0-9]+')->name('update');
    Route::post('/destroy', 'ExpenditureController@destroy')->name('destroy');
});

//RUTAS PARA PROSPECTOS
Route::middleware(['auth','web'])->name('handbills.')->prefix('handbills')->group(function(){
    Route::get('/','HandbillController@index')->name('index');
    Route::get('/create','HandbillController@create')->name('create');
    Route::get('/edit/{id}','HandbillController@edit')->where('id','[0-9]+')->name('edit');

    Route::post('/store','HandbillController@store')->name('store');
    Route::post('/update/{id}','HandbillController@update')->where('id','[0-9]+')->name('update');
    Route::post('/destroy','HandbillController@destroy')->name('destroy');
});

//RUTAS PARA SERVICIOS
Route::middleware(['auth','web'])->name('services.')->prefix('services')->group(function(){
    Route::get('/', 'ServiceController@index')->name('index');
    Route::get('/create','ServiceController@create')->name('create');
    Route::get('/edit/{id}','ServiceController@edit')->where('id','[0-9]+')->name('edit');
    Route::get('/get_services/{price}','ServiceController@get_services')->name('get_services');

    Route::post('/store','ServiceController@store')->name('store');
    Route::post('/destroy','ServiceController@destroy')->name('destroy');
    Route::post('/update/{id}','ServiceController@update')->where('id','[0-9]+')->name('update');
});

//RUTAS PARA CLIENTES
Route::middleware(['auth','web'])->name('clients.')->prefix('clients')->group(function(){
    Route::get('/','ClientController@index')->name('index');
    Route::get('/create','ClientController@create')->name('create');
    Route::get('/check_rfc/{rfc}','ClientController@check_rfc')->name('check_rfc');
    Route::get('/price_list/{id}','ClientController@price_list')->name('price_list');

    Route::post('/store','ClientController@store')->name('store');
});

// RUTAS PARA COTIZACIONES
Route::middleware(['auth','web'])->name('quotations.')->prefix('quotations')->group(function(){
    Route::get('/', 'QuotationController@index')->name('index');
    Route::get('/create','QuotationController@create')->name('create');
    Route::get('/get_quotation/{id}','QuotationController@get_quotation')->name('get_quotation');

    Route::post('/store','QuotationController@store')->name('store');
    Route::post('/destroy','QuotationController@destroy')->name('destroy');
});

// RUTAS PARA REMISIONES
Route::middleware(['web','auth'])->name('referrals.')->prefix('referrals')->group(function(){
    Route::get('/','ReferralController@index')->name('index');
    Route::get('/create','ReferralController@create')->name('create');

    Route::post('/store','ReferralController@store')->name('store');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>@yield('title','Chronos')</title>

        <script src="{{asset('js/all.min.js')}}" charset="utf-8"></script>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{asset('css/bootstrap.css')}}">
        @auth
            <link rel="stylesheet" href="{{asset('css/layouts/auth.css')}}">
        @endauth
        @yield('styles')
    </head>
    <body>
        <div id="app">
            @guest

                <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                    <a class="navbar-brand" href="#">
                        {{-- <img src="" alt=""> --}}
                        Chronos
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#initial-navbar">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="initial-navbar">
                        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                            <li class="nav-item @yield('login')">
                                <a href="{{route('login')}}" class="nav-link">
                                    <i class="fas fa-user mr-2"></i>
                                    {{__('Iniciar sesión')}}
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>

            @else
                <div id="sidenav" class="sidenav">
                    <div class="container-fluid">
                        <div class="row px-0">
                            <div class="col-12 text-right sticky-top">
                                <button type="button" class="btn btn-link button-menu">
                                    <i class="fas fa-times fa-lg icon-close"></i>
                                </button>
                            </div>
                            <div class="col-12 text-center sticky-top top-div">
                                <img src="{{asset('images/logo.png')}}" alt="" class="img-fluid" width="130px"><br>
                            </div>
                            <div class="col-12 form-row mt-3">
                                <div class="col-6 float-left">
                                    <p class="user-name ml-auto">
                                        {{Auth::user()->name}}
                                    </p>
                                </div>
                                <div class="col-6 form-row config">
                                    <a href="#" class="btn-link ml-auto my-auto">
                                        <i class="fas fa-cog fa-lg"></i>
                                    </a>
                                    <button type="button" class="btn btn-link" data-toggle="modal" data-target="#logout">
                                        <i class="fas fa-power-off fa-lg"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="col-12 mt-4 px-0 list-options">

                                <a href="#" class="side-link @yield('dashboard') text-decoration-none">
                                    <i class="far fa-object-group fa-lg mr-3"></i>
                                    {{__('DASHBOARD')}}
                                </a>
                                {{-- MENU INVENTARIO --}}
                                <a href="#" class="side-link dropdown-btn text-decoration-none" data-target="#dropdown-inv">
                                    <i class="far fa-caret-square-down fa-lg mr-3"></i>
                                    {{__('INVENTARIO')}}
                                    <i class="fa fa-caret-down ml-5"></i>
                                </a>
                                <div class="dropdown-container hide" id="dropdown-inv">
                                    <a href="{{route('consumables.index')}}" class="side-link link-dropdown @yield('consumibles') text-decoration-none">
                                        CONSUMIBLES
                                    </a>
                                    <a href="{{route('equipment.index')}}" class="side-link link-dropdown @yield('equipo') text-decoration-none">
                                        EQUIPO
                                    </a>
                                    <a href="{{route('loans.index')}}" class="side-link link-dropdown @yield('prestamos') text-decoration-none">
                                        PRÉSTAMOS
                                    </a>
                                    <a href="{{route('income_orders.index')}}" class="side-link link-dropdown @yield('orden_entrada') text-decoration-none">
                                        ORDENES DE ENTRADA
                                    </a>
                                </div>
                                {{-- MENU COMPRAS --}}
                                <a href="#" class="side-link dropdown-btn text-decoration-none" data-target="#dropdown-comp">
                                    <i class="fas fa-cart-plus fa-lg mr-3"></i>
                                    {{__('COMPRAS')}}
                                    <i class="fa fa-caret-down ml-5"></i>
                                </a>
                                <div class="dropdown-container hide" id="dropdown-comp">
                                    <a href="{{route('suppliers.index')}}" class="side-link link-dropdown @yield('proveedores') text-decoration-none">
                                        PROVEEDORES
                                    </a>
                                    <a href="{{route('purchase_orders.index')}}" class="side-link link-dropdown @yield('orden_compra') text-decoration-none">
                                        ÓRDENES DE COMPRA
                                    </a>
                                    <a href="{{route('expenditures.index')}}" class="side-link link-dropdown @yield('gastos') text-decoration-none">
                                        GASTOS
                                    </a>
                                </div>
                                {{-- MENU VENTAS --}}
                                <a href="#" class="side-link dropdown-btn text-decoration-none" data-target="#dropdown-vent">
                                    <i class="far fa-money-bill-alt fa-lg mr-3"></i>
                                    {{__('VENTAS')}}
                                    <i class="fa fa-caret-down ml-5"></i>
                                </a>
                                <div class="dropdown-container hide" id="dropdown-vent">
                                    <a href="{{route('handbills.index')}}" class="side-link link-dropdown @yield('prospectos') text-decoration-none">
                                        PROSPECTOS
                                    </a>
                                    <a href="{{route('clients.index')}}" class="side-link link-dropdown @yield('clientes') text-decoration-none">
                                        CLIENTES
                                    </a>
                                    <a href="{{route('services.index')}}" class="side-link link-dropdown @yield('servicios') text-decoration-none">
                                        SERVICIOS
                                    </a>
                                    <a href="{{route('quotations.index')}}" class="side-link link-dropdown @yield('cotizaciones') text-decoration-none">
                                        COTIZACIONES
                                    </a>
                                    <a href="{{route('referrals.index')}}" class="side-link link-dropdown @yield('remisiones') text-decoration-none">
                                        REMISIONES
                                    </a>
                                </div>
                                {{-- MENU REPORTES --}}
                                <a href="#" class="side-link dropdown-btn text-decoration-none" data-target="#dropdown-repo">
                                    <i class="fas fa-chart-line fa-lg mr-3"></i>
                                    {{__('REPORTES')}}
                                    <i class="fa fa-caret-down ml-5"></i>
                                </a>
                                <div class="dropdown-container hide" id="dropdown-repo">

                                </div>
                                {{-- MENU AJUSTES --}}
                                <a href="#" class="side-link dropdown-btn text-decoration-none" data-target="#dropdown-ajus">
                                    <i class="fas fa-sliders-h fa-lg mr-3"></i>
                                    {{__('AJUSTES')}}
                                    <i class="fa fa-caret-down ml-5"></i>
                                </a>
                                <div class="dropdown-container hide" id="dropdown-ajus">
                                    <a href="#" class="side-link link-dropdown @yield('cotizaciones') text-decoration-none">
                                        USUARIOS
                                    </a>
                                    <a href="#" class="side-link link-dropdown @yield('roles') text-decoration-none">
                                        ROLES
                                    </a>
                                    <a href="#" class="side-link link-dropdown @yield('divisas') text-decoration-none">
                                        DIVISAS
                                    </a>
                                    <a href="#" class="side-link link-dropdown @yield('configuracion') text-decoration-none">
                                        CONFIGURACIÓN
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endguest

            <main>
                @auth
                    <nav class="navbar navbar-dark bg-dark button-nav sticky-top">
                        <button type="button" class="btn btn-link navbar-brand button-menu">
                            <i class="fas fa-bars fa-lg"></i>
                        </button>
                        <span class="navbar-brand mr-auto">@yield('top-title')</span>
                    </nav>
                @endauth

                @yield('content')
            </main>

            @include('Notifications')
            @include('layouts.logout')

            <script src="{{asset('js/jquery-3.4.1.min.js')}}" charset="utf-8"></script>
            <script src="{{asset('js/popper.min.js')}}" charset="utf-8"></script>
            <script src="{{asset('js/bootstrap.min.js')}}" charset="utf-8"></script>
            <script src="{{asset('js/TweenMax.min.js')}}" charset="utf-8"></script>
            <script src="{{asset('js/notifications.js')}}" charset="utf-8"></script>

            @auth
            <script src="{{asset('js/sidebar.js')}}" charset="utf-8"></script>
            @endauth

            @yield('scripts')
        </div>
    </body>
</html>

resources/views/layouts/logout.blade.php
<div class="modal fade" id="logout" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content modal-design">
            <div class="modal-header">
                <h5 class="modal-title">{{__('ATENCIÓN')}}</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h6 class="text-center">{{__('¿Realmente desea cerrar sesión?')}}</h6>
            </div>
            <div class="modal-footer">
                <form action="{{route('logout')}}" method="post">
                    @csrf
                    <button type="button" class="btn btn-link btn-modal-cancelar" data-dismiss="modal">
                        {{__('CANCELAR')}}
                    </button>
                    <button type="submit" class="btn btn-danger rounded-0 btn-modal-aceptar">
                        {{__('ACEPTAR')}}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>